### ISSUE TITLE
请问有BIOS的什么特殊设置么，我这边能进入MacOS系统但是过几分钟就死机重启了，同样的系统版本

### ISSUE THREAD

**Issue by deepkolos** [plusl894860970/H410D4IPC_i5-10400_HD630_OC#2]
请问有BIOS的什么特殊设置么，我这边能进入MacOS系统但是过几分钟就死机重启了，同样的系统版本，不知道大佬是否遇过这个问题

enable above 4g, 
disable cfg lock, 
64mb

**Comment by plus1998** [comment]
BIOS都是黑苹果常规的设置
关闭选项：Fast Boot、CSM、CFG Lock、Secure Boot、VT-d
开启选项：XHCI-Handoff
关于你重启的问题，你可以描述的详细一些。比如用什么线连接显示器，死机的情况可以描述一下，另外推荐你注入显示器的EEID

**Comment by deepkolos** [comment]
显示器是便携屏幕 HDMI连接，重启是主板的蜂鸣器会吱吱几下电流声音然后就立即重启了，XHCI-Handoff我没开启，下班后试试，谢谢大佬

**Comment by plus1998** [comment]
你可以试试热插拔HDMI会不会重启。怀疑这个问题导致的。

**Comment by deepkolos** [comment]
OK, 是指不连接显示器进入macos 等进入之后再接入HDMI，还是进入系统之后再拔出再接入么
我也试试DP转HDMI
