### ISSUE TITLE
实测i3可用。

### ISSUE THREAD

**Issue by sirizhou** [plusl894860970/H410D4IPC_i5-10400_HD630_OC#4]
实测i3可用，但是无法使用有线网，HDMI无声音输出。

**Comment by plusl894860970** [comment]
![image](https://user-images.githubusercontent.com/44946497/100690408-68823300-33c1-11eb-8c55-e75a2f46bfbc.png)
关于以太网，看下系统报告里面的驱动信息

**Comment by plus1998** [comment]
> 实测i3可用，但是无法使用有线网，HDMI无声音输出。

![image](https://user-images.githubusercontent.com/44946497/100690450-85b70180-33c1-11eb-802d-781e953610f5.png)
关于以太网，看下系统报告里的驱动信息

**Comment by plus1998** [comment]
无反馈，关闭了哦。
