### ISSUE TITLE
睡眠

### ISSUE THREAD

**Issue by tianxdy** [plusl894860970/H410D4IPC_i5-10400_HD630_OC#5]
这个主板睡眠了能唤醒吗？我还没有装才把主板和cpu买回来，但是听说睡眠不太行

**Comment by plus1998** [comment]
DP唤醒正常。HDMI暂无法唤醒/及其难以唤醒。

**Comment by plus1998** [comment]
长时间无回应，关闭了

**Comment by fkpwolf** [comment]
HDMI确实一睡不起，好像是通病，我另外一款h370加了framebuffer patch也是一样的问题。

**Comment by fkpwolf** [comment]
Added `igfxonln=1` boot argument and force-online IGPU property force online status for all displays
